---
username: mishraprafful
obsidian_repo: git@github.com:mishraprafful/notes.git
dotfiles_repo: git@github.com:mishraprafful/dotfiles.git
passwords_repo: git@github.com:mishraprafful/password-store.git

homebrew_installed_packages:
  - go
  - gopass
  - zsh
  - k9s
  - kubernetes-cli
  - kubectx
  - docker
  - yadm
  - starship
  - zsh-syntax-highlighting
  - zsh-autosuggestions

homebrew_taps:
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - miniconda
  - visual-studio-code
  - caffeine
  - slack
  - spotify
  - obsidian
  - iterm2
  - gitify
  - rectangle
