---
homebrew_installed_packages:
  - go
  - gopass
  - zsh
  - k9s
  - kubernetes-cli
  - kubectx
  - docker
  - yadm

homebrew_taps:
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - miniconda
  - visual-studio-code
  - caffeine
  - slack
  - spotify
  - obsidian
  - iterm2
  - miniconda
  - obsidian
  - gitify
