---
- name: Setup Local Machine
  hosts: localhost
  connection: local

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: [homebrew]
  tasks:
    - name: Setup dotfiles from remote
      ansible.builtin.import_tasks: tasks/dotfiles-setup.yml
    # - import_tasks: tasks/gopass-config.yml
    - name: Setup and Install fonts for terminal use
      ansible.builtin.import_tasks: tasks/setup-fonts.yml
    - name: Initialize Conda Installation
      ansible.builtin.import_tasks: tasks/miniconda-init.yml


